- hosts: localhost                           # we don't use inventory for the switches
  connection: local                          # Run everything on the control node
  collections:
  - brocade.fos                              # Reference the brocade.fos collection
  gather_facts: False                        # We don't need to gather facts
  vars_prompt:                               # We don't store passwords so prompt switch password
  - name: brocade_password
    prompt: Enter Brocade password

  tasks:
  - name: Create aliases                     # Descriptive name for the task
    brocade_zoning_alias:
      credential:
        fos_ip_addr: switch_name_or_ip       # CHANGEME host name or IP address of the switch
        fos_user_name: admin                 # CHANGEME username to connect to the switch
        fos_password: "{{brocade_password}}" # Use the prompted password
        https: False                         # Set to True to use https instead of http
      vfid: -1                               # CHANGEME use the logical switch ID if activated
      aliases:
      - name: ALIAS_1                        # CHANGEME name of the first alias
        members:
        - 11:22:33:44:55:66:77:88            # CHANGEME WWPN to put in the first alias
      - name: ALIAS_2                        # CHANGEME name of the second alias
        members:
        - 22:22:33:44:55:66:77:88            # CHANGEME first WWPN to put in the second alias
        - 22:22:33:44:55:66:77:89            # CHANGEME second WWPN to put in the second alias
